// export const mockReservations = [
//   {
//     id: "1",
//     freelancer: "Elena Valeska",
//     service: "에디토리얼 웨딩 스냅",
//     date: "2024. 06. 14",
//     location: "서울 용산구 한남동",
//     price: "₩2,400,000",
//     status: "confirmed",
//     img: "https://picsum.photos/seed/elena/200/200",
//   },
//   {
//     id: "2",
//     freelancer: "Sage & Petal",
//     service: "웨딩 플로럴 풀패키지",
//     date: "2024. 06. 14",
//     location: "서울 강남구 청담동",
//     price: "₩1,500,000",
//     status: "pending",
//     img: "https://picsum.photos/seed/sage/200/200",
//   },
//   {
//     id: "3",
//     freelancer: "Marcus Chen",
//     service: "파인다이닝 케이터링",
//     date: "2024. 04. 20",
//     location: "경기도 파주",
//     price: "₩3,200,000",
//     status: "completed",
//     img: "https://picsum.photos/seed/mchen/200/200",
//   },
//   {
//     id: "4",
//     freelancer: "Luna Strings",
//     service: "현악 사중주 2시간",
//     date: "2024. 03. 10",
//     location: "서울 종로구",
//     price: "₩1,200,000",
//     status: "cancelled",
//     img: "https://picsum.photos/seed/luna/200/200",
//   },
// ] as const;
